chore: improve README.md standardization
hirosystems/clarinet pull request #1075
Opened 2023-07-13 02:45 UTC by smcclellan

2023-07-13 10:44 UTC, hugocaillard requested changes
Few change to adapt the template to clarinet

2023-07-13 10:44 UTC, hugocaillard commented on .github/CONTRIBUTING.md
> +To help you get familiar with our contribution process, we have a list of [good first issues](../../issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) that contain bugs that have a relativ
```suggestion
To help you get familiar with our contribution process, we have a list of [good first issues](../../issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) that contain enhancements or bugs that have a relatively limited scope. This is a great place to get started.
```

2023-07-13 10:44 UTC, hugocaillard commented on .github/ISSUE_TEMPLATE/bug_report.md
> +Time stamp
```suggestion
```
Not applicable to clarinet I think

2023-07-13 10:44 UTC, hugocaillard commented on .github/ISSUE_TEMPLATE/bug_report.md
> + - Version [e.g. 22]
```suggestion
```

No applicable

2023-07-13 10:44 UTC, hugocaillard commented on .github/ISSUE_TEMPLATE/bug_report.md
> + - Version [e.g. 22]
```suggestion
**Environment (please complete the following information):**
 - OS (version): [e.g. macOS (13.4.1)]
 - Docker version [e.g. 24.0.4]
 - Clarinet version [e.g. 1.7.0] - Please use the latest version
```

2023-07-13 17:43 UTC, smcclellan commented
Thank you @hugocaillard!

2023-07-17 11:12 UTC, hugocaillard approved these changes

2023-07-17 11:12 UTC, merged