Edit typos and language fixes in the 'Clarinet Integrate' doc
hirosystems/clarinet pull request #1123
Opened 2023-08-07 20:15 UTC by krishna-chaitanya-piratla

### Description
Edit typos and language fixes in the 'Clarinet Integrate' doc

#### Breaking change?
No

2023-08-10 14:05 UTC, LakshmiLavanyaKasturi requested changes

2023-08-10 14:05 UTC, LakshmiLavanyaKasturi commented on docs/feature-guides/clarinet-integrate.md
> +The Clarinet Integrate feature enables you to easily integrate your existing smart contracts with the blockchain in a local testing environment,allowing you to to validate and verify your smart contr
```suggestion
The Clarinet Integrate feature enables you to easily integrate your existing smart contracts with the blockchain in a local testing environment, allowing you to validate and verify your smart contract on an actual blockchain. While unit testing (the process of testing your code to ensure it works correctly) is a valuable way to test your code before implementation, certain features cannot be verified during unit testing, such as how your smart contract interacts with proof of transfer or the Bitcoin chain. Clarinet Integrate provides these additional tests.
```

2023-08-10 14:05 UTC, LakshmiLavanyaKasturi commented on docs/feature-guides/clarinet-integrate.md
> +Setting up and configuring your devnet can be time-consuming. Clarinet Integrate speeds up the deployment process with an embedded orchestrator tool that enables you to run your own devnet network ev
```suggestion
Setting up and configuring your own devnet can be time-consuming. Clarinet Integrate speeds up the deployment process with an embedded orchestrator tool that enables you to run your own devnet network even when offline.
```

2023-08-10 14:57 UTC, krishna-chaitanya-piratla reviewed
Incorporated the suggestions. The PR is ready for a second review. Thank you!

2023-08-11 16:56 UTC, LakshmiLavanyaKasturi approved these changes

2023-08-11 16:56 UTC, merged