deployment apply -y option
hirosystems/clarinet pull request #1135
Opened 2023-08-23 14:55 UTC by CAGS295

### Description
The user prompt to confirm a `clarinet deployments apply` makes it hard to use in automated scripts. Adding an option '-y' to pre-accept the deployment would allow users to automate deployments.

2023-08-23 14:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/hirosystems/clarinet?pullRequest=1135) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/hirosystems/clarinet?pullRequest=1135) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/hirosystems/clarinet?pullRequest=1135) it.</sub>

2023-08-23 15:02 UTC, sabbyanandan commented
@CAGS295: This would be very helpful toggle, for sure! 👏🏽 Thank you for your contribution. One of the Clarinet team members will review and collaborate with you shortly.

Please also share how Clarinet is running in your infra; any info about CI/CD automation can be helpful context. With that, we can explore additional optimizations in this workflow and unlock advanced use cases.

2023-08-28 17:15 UTC, CAGS295 commented
This is my toy example:
Launch a node.
Wait for the stacks api to be up.
Use block height as a proxy for the node being ready.
Apply deployments. (no way to skip the prompt afaik)
Run tests.
Kill the node.

```bash
#!/usr/bin/env bash
set -eou >/dev/null

API_URL=http://localhost:3999/v2/info
DEV_READY_HEIGHT=137

clarinet integrate --no-dashboard >/dev/null &
CLARINET_PID=$!
echo "clarinet PID $CLARINET_PID"

# Wait until API is up
echo "Waiting on Stacks API"
while ! curl -s $API_URL >/dev/null; do
    sleep 1
done
echo "Waiting on burn block height $DEV_READY_HEIGHT"
#Wait until devnet is ready, epoch 2.4?.
while [ "$(curl -s $API_URL | jq '.burn_block_height')" -lt $DEV_READY_HEIGHT ]; do
    sleep 2
done
# Apply extra deployments
clarinet deployment apply -p integration/deployments/bootstrap.devnet-plan.yml
#Run tests
yarn test

kill -s INT $CLARINET_PID
```

2023-08-28 17:21 UTC, sabbyanandan commented
> This is my toy example: Launch a node. Wait for the stacks api to be up. Use block height as a proxy for the node being ready. Apply deployments. (no way to skip the prompt afaik) Run tests. Kill the node.

@CAGS295: This is very helpful! Many thanks for the clarification.

2023-08-28 18:22 UTC, lgalabru requested changes
Thanks @CAGS295! The `-y` option could be confusing, what's your take on replicating the behavior we have in some other subcommands?

```rust
    /// Use on disk deployment plan (prevent updates computing)
    #[clap(
        long = "use-on-disk-deployment-plan",
        short = 'd',
        conflicts_with = "use-computed-deployment-plan"
    )]
    pub use_on_disk_deployment_plan: bool,
    /// Use computed deployment plan (will overwrite on disk version if any update)
    #[clap(
        long = "use-computed-deployment-plan",
        short = 'c',
        conflicts_with = "use-on-disk-deployment-plan"
    )]
    pub use_computed_deployment_plan: bool,
```

2023-08-28 20:48 UTC, CAGS295 commented
good. If we can settle on a long option, picking the short one should be straightforward. I do lean towards concise long options. Nobody likes flooding the console with many long options.

2023-09-07 13:57 UTC, hugocaillard submitted a review, later dismissed
LGTM!
Thanks for your contribution @CAGS295!

@lgalabru is `#[clap(long = "skip-prompt", short = 's')]` okay for you?

2023-09-07 16:57 UTC, lgalabru commented
A skip prompt does not seem like a good idea to me.
How about adding the following flags:

```rust
    /// Use on disk deployment plan (prevent updates computing)
    #[clap(
        long = "use-on-disk-deployment-plan",
        short = 'd',
        conflicts_with = "use-computed-deployment-plan"
    )]
    pub use_on_disk_deployment_plan: bool,
    /// Use computed deployment plan (will overwrite on disk version if any update)
    #[clap(
        long = "use-computed-deployment-plan",
        short = 'c',
        conflicts_with = "use-on-disk-deployment-plan"
    )]
    pub use_computed_deployment_plan: bool,
```

So if a developer wants to skip prompt, they chose the right flag for forcing the usage of the deployment on disk, or the computed plan.

2023-09-15 08:36 UTC, hugocaillard commented
@CAGS295 Can you sign the CLA please? https://github.com/hirosystems/clarinet/pull/1135#issuecomment-1690116162

2023-09-19 13:03 UTC, lgalabru approved these changes
Looking great, this enhancement is going to be super useful! Thank you @CAGS295 for bearing with me :)

2023-09-19 13:06 UTC, merged