chore: remove chainhook subcommands
hirosystems/clarinet pull request #1328
Opened 2024-01-23 18:46 UTC by tippenein

closes #1308

2024-01-23 18:51 UTC, sabbyanandan commented
@tippenein: 💥! 

More importantly, I love this:
![image](https://github.com/hirosystems/clarinet/assets/1562654/96ccf9df-89eb-456d-b96f-71ca6fc8891a)

2024-01-23 22:04 UTC, hugocaillard commented
Thanks @tippenein. And happy new year! 🎉 

What do you think about printing a message explaining that `clarinet chainhook` is no longer available (because it wasn't maintained)? And maybe suggest alternatives? (cc @MicaiahReid) 

No hurry on this, I think we'll hold the PR for after the next release (2.2.0)

2024-01-23 23:03 UTC, tippenein commented
hey @hugocaillard 
Yeah that sounds fine by me 👌

2024-02-08 20:16 UTC, MicaiahReid requested changes
Hey @tippenein, thanks for the PR!

I had some time to give this one some thought, and I think we only actually want part of this change. 

Clarinet had the `clarinet chainhook new` command that would generate chainhooks that are no longer compatible with the actual Chainhook tool. Now that Chainhook is a standalone tool, we don't need to have the generation of these files inside of Clarinet.

However, Clarinet still finds a user's chainhooks in their working directory and automatically registers them with their devnet, which is a really helpful feature that we actually just released [a guide](https://docs.hiro.so/chainhook/guides/register-chainhooks-on-devnet) on.

Would you be able to revert the changes that remove chainhook from the devnet?

2024-02-08 20:16 UTC, MicaiahReid commented on components/clarinet-cli/src/frontend/cli.rs
> +        yellow!("Find more information on the DevNet here: https://docs.hiro.so/clarinet/guides/how-to-run-integration-environment")
```suggestion
        yellow!("Find more information on the devnet here: https://docs.hiro.so/clarinet/guides/how-to-run-integration-environment")
```
I think that across most of our Hiro docs we just use `devnet`.

2024-02-08 20:16 UTC, MicaiahReid commented on components/clarinet-cli/src/devnet/start.rs
> -    let hooks = match load_chainhooks(
This is used to load chainhook files from the user's directory and to auto-register them with the devnet. This is a useful feature that we want to keep.

2024-02-08 20:16 UTC, MicaiahReid commented on components/stacks-network/src/chainhooks.rs
> -use chainhook_sdk::chainhooks::types::{ChainhookConfig, ChainhookFullSpecification};
We also want to keep the stuff in this file!

2024-02-08 20:16 UTC, MicaiahReid commented on components/stacks-network/src/chains_coordinator.rs
> -use chainhook_sdk::chainhooks::types::ChainhookConfig;
We'll want to revert the changes in this file so that we still register hooks with the devnet.

2024-02-08 20:16 UTC, MicaiahReid commented on components/stacks-network/src/lib.rs
> -pub use chainhooks::{check_chainhooks, load_chainhooks, parse_chainhook_full_specification};
We'll want to revert the changes in this file.

2024-02-08 20:16 UTC, MicaiahReid commented on components/stacks-network/src/main.rs
> +use stacks_network::do_run_chain_coordinator;
We'll want to revert the changes in this file.

2024-02-08 22:38 UTC, tippenein commented
@MicaiahReid thanks for the feedback. So, we're essentially only deprecating the `chainhook new` ?

This is what it looks like currently:
![Screenshot 2024-02-08 at 2 36 05 PM](https://github.com/hirosystems/clarinet/assets/1235263/759bebf6-1832-4cea-b89f-844a6961f028)
![Screenshot 2024-02-08 at 2 36 28 PM](https://github.com/hirosystems/clarinet/assets/1235263/39aa7af4-a5be-4d5b-ac89-12dd62701061)

2024-02-09 15:15 UTC, MicaiahReid commented
> So, we're essentially only deprecating the chainhook new

@tippenein Apologies for the mixed messaging here. We can also deprecate `chainhook check` and `chainhook deploy`.
If, after deprecating those, you find some helper functions in the `stacks-network` component that are no longer used, those can be removed (for example, I think we'll be able to do away with the `check_chainhooks` function).

What will need to remain is all code that is used _by_ the `stacks-network` to load the chainhooks into a devnet.

2024-02-09 20:52 UTC, tippenein commented
@MicaiahReid Yea that makes total sense. It should be good now 👍  lmk

2024-02-12 15:14 UTC, MicaiahReid approved these changes
Looks good, thanks @tippenein!

2024-02-12 17:08 UTC, hugocaillard commented
Thanks @tippenein!
I'm merging now

2024-02-12 17:08 UTC, merged