Support workspaces
hirosystems/clarinet pull request #1500
Opened 2024-07-09 13:57 UTC by bradleyayers

The location of `node_modules` is not guaranteed to be relative to the current directory (e.g. in yarn workspaces). 

A better solution here is to update package.json `exports` to include the file.

### Description

#### Breaking change?

### Example

---

### Checklist

- [ ] Tests added in this PR (if applicable)

2024-07-09 13:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/hirosystems/clarinet?pullRequest=1500) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/hirosystems/clarinet?pullRequest=1500) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/hirosystems/clarinet?pullRequest=1500) it.</sub>

2024-07-09 14:10 UTC, hugocaillard commented on components/clarinet-sdk/src/vitest/index.ts
> +import { join } from "node:path";
You are not using it right?

2024-07-09 14:13 UTC, hugocaillard commented
Good catch, thank you for opening this PR @bradleyayers 
I'll give it a try and need to make sure it doesn't have unwanted side effectsx

2024-07-10 00:35 UTC, bradleyayers commented
One thing to check is whether require.resolve is the correct API to use for ESM output, i'm not sure. And also the point about instead of doing a manual path concat i think it's better if the target file is made one of the exports in package.json.

2024-07-18 16:55 UTC, hugocaillard requested changes
remove unused imports

2024-07-18 16:57 UTC, hugocaillard commented
Hey @bradleyayers 
Sorry we couldn't get this merged before, now there is conflict. The file has been moved, you basically need to migrate the your change in this file:  `components/clarinet-sdk/node/src/vitest/index.ts`.

Do you think you'll have time to do it or should I take over the task (and credit you in my commit)?

2024-07-19 08:56 UTC, bradleyayers commented
Please take this over that would be amazing, thank you.

2024-07-22 12:48 UTC, hugocaillard commented
Superseded by #1514

2024-07-22 12:48 UTC, closed without merging