Clarinet format
hirosystems/clarinet pull request #1609
Opened 2024-11-12 19:19 UTC by tippenein

fix: #606 

Features:
Adds `format`/`fmt` to clarinet
```
  -m, --manifest-path <MANIFEST_PATH>      
  -f, --file <FILE>                        If specified, format only this file
  -l, --max-line-length <MAX_LINE_LENGTH>  
  -i, --indent <INDENTATION>               indentation size, e.g. 2
  -t, --tabs                               use tabs instead of spaces
      --dry-run                            
      --in-place 
```

remaining work

- [x] fix pre- and post-comments
- [x] top level max-line breaking
- [x] @format-ignore comments (possibly pushed off until post-mvp)
- [x] passing golden test suite

soon:
- LSP/VSCode integration (https://github.com/hirosystems/clarinet/pull/1632)

2024-11-15 14:46 UTC, hugocaillard commented on components/clarinet-format/Cargo.toml
> +clarity-repl = { path = "../clarity-repl" }
We might not need `clarity-repl` here, but instead we can directy depend on `clarity`.
I'm not a big fan of `clarity-repl` re-exporting all of the VM, and it creates a dependency mess.

```toml
clarity = { workspace = true }
```

Eventually, you will also have to manage the clarity feature like for native and wasm (you can see this pattern in other Clarinet components, such as the repl

```toml
[features]
default = ["cli"]
cli = [
    "clarity/canonical",
    "clarity/developer-mode",
    "clarity/devtools",
    "clarity/log",
]
wasm = [
    "clarity/wasm",
    "clarity/developer-mode",
    "clarity/devtools",
]
```

2024-12-05 14:36 UTC, hugocaillard commented on components/clarinet-cli/src/frontend/cli.rs
> +    pub code_path: Option<String>,
By default, the formatter should be based on the manifest.
Load the manifest like other comamnds do (looking for `./Clarinet.toml`). And an option should allow to specify the manifest path

2024-12-05 14:36 UTC, hugocaillard commented on components/clarinet-cli/src/frontend/cli.rs
> +            let sources = get_source_with_path(cmd.code_path, cmd.file);
Get the contracts from the manifest

2025-01-03 01:16 UTC, tippenein commented
Giving an update here. 

1. We need a way of organizing the traversal to identify expression-blocks to wrap. Currently, you could attempt to check line lengths and wrap conditionally as you go (tried this), but it won't work easily if you need multiple wraps per block. My thought is we need a `Wrap` type that's just used while traversing the PSEs and checks the span column length and start_line diff to turn wrapping on or off.

2. We need to figure out `ignored_expr` for skipping formatting if specified. The function that exists is basically a stub but it _should_ be possible to reconstruct the source from the PSE spans..

3. There's a fair amount of nested indentation that fails within golden tests (the unit tests don't test this much). I would guess that a better way of handling indentation wrapping would ease this (rather than the current attempt of passing in `previous_indentation` and constructing the string from that.. Very error prone.

4. This is more of a refactor, but basically we're doing way too much arg passing. There's a branch ([`experiment-with-accumulator`](https://github.com/hirosystems/clarinet/commit/f619b0a6fa15749c4eb390033ca4053d9df1cd6c#diff-bdfb6363ac810ef4d419caf59fba1e9b747a6a281fbd56b6d87a70cf66c226f4R107-R149)) which i attempted to use an Accumulator struct to pass around the relevant info for constructing the result but it got a bit hairy with dereferencing and ultimately stack overflowed when I got it compiling. It's probably worth looking into because it would help fix 3 implicitly with the `indent` `dedent` and `newline` methods on `Accumulator`

2025-02-04 23:35 UTC, hugocaillard reviewed
Took a quick look at it, I left a few comments/questions in the intended golden outputs. Just some of the most visible patterns of issues that seems important to me

2025-02-04 23:35 UTC, hugocaillard commented on components/clarinet-format/Cargo.toml
> +# clarity-repl = { path = "../clarity-repl" }
can be removed

2025-02-04 23:35 UTC, hugocaillard commented on components/clarinet-format/tests/golden-intended/alex-transfer.clar
> +                )
There are some indentation issues here right? (double indent within `if` and mis-aligned closing parenthesis lines 58 and 59
```
               (ids-to-treasury
                    (if (is-eq no-to-treasury u0)
                        (list)
                        (unwrap-panic
                            (slice? 
                                owned-by-sender
                                (- (len owned-by-sender) no-to-treasury)
                                (len owned-by-sender)
                            )
                        )
                    )
                )
```

2025-02-04 23:35 UTC, hugocaillard commented on components/clarinet-format/tests/golden-intended/clarity-bitcoin.clar
> +			{
Could/should the new line before `{` be avoided?
Looks like there's this pattern in all `(ok <tuple>)`

2025-02-04 23:35 UTC, hugocaillard commented on components/clarinet-format/tests/golden-intended/clarity-bitcoin.clar
> +					(parsed-u16
missing indentation?

2025-02-04 23:35 UTC, hugocaillard commented on components/clarinet-format/tests/golden-intended/clarity-bitcoin.clar
> +					)
What is the rule/logic for new lines here?
I feel like I'd be happy with something like
```clarity
            (let (
							;; next eight bytes is the varint
							(parsed-u64 (try! (read-uint64 {
								txbuff: tx,
								index: (+ u1 ptr)
							})))
						)
```

2025-02-04 23:35 UTC, hugocaillard commented on components/clarinet-format/tests/golden-intended/clarity-bitcoin.clar
> +						{
The new line before `{` seems unnecessary to me as well here

2025-02-04 23:35 UTC, hugocaillard commented on components/clarinet-format/tests/golden-intended/clarity-bitcoin.clar
> +			)
Missing indentation level?

2025-02-04 23:35 UTC, hugocaillard commented on components/clarinet-format/tests/golden-intended/tuple.clar
> +        use-as-collateral: bool,      }
Missing new line before `}`?

2025-02-05 05:31 UTC, tippenein commented on components/clarinet-format/tests/golden-intended/clarity-bitcoin.clar
> +			{
it depends on the source. if it's over max width it'll newline it. This could be changed but it starts looking weird if you start a map on the same line as `(ok ..` and then dump all the rest of the keys on the next indented lines

```
(ok { something: 1,
  a: b,
  c: d
  }
)
```

Oh, maybe I see your point. It should be this?

```
(ok {
  something: 1,
 ```

2025-02-05 05:35 UTC, tippenein commented on components/clarinet-format/tests/golden-intended/clarity-bitcoin.clar
> +					)
It does the paren lining up here: https://github.com/hirosystems/clarinet/pull/1609/files#diff-bdfb6363ac810ef4d419caf59fba1e9b747a6a281fbd56b6d87a70cf66c226f4R779-R781

It's quite easy to stack the closing parens `)))` by not including the above logic. 

Maybe it makes sense in some situations, but this is generic inner content handling. It's also worsened by how bad tabs look here, I think..

2025-02-05 05:38 UTC, tippenein commented on components/clarinet-format/tests/golden-intended/clarity-bitcoin.clar
> +			)
interesting.. `fold` wrapped wrong. Probably `inner_content` bug.. Will check 👌

2025-02-05 05:44 UTC, tippenein commented on components/clarinet-format/tests/golden-intended/alex-transfer.clar
> +                )
The double indent _is_ intended. The tricky part here is that the double indent is for situations where the `if` is nested inside something, like

```
(key (if (...)
    (list) ;; double indent here
    ...
```

but since the line was too long, it got broken up onto separate lines..

Open to whatever changes, but I'll fix the `unwrap-panic` indenting since that's clearly wrong

2025-02-05 09:32 UTC, csgui reviewed
Hey @tippenein! Well done on this code formatting implementation. I have added some remarks that might be worth checking. Tks!

2025-02-05 09:32 UTC, csgui commented on components/clarinet-format/src/formatter/mod.rs
> +            if current_line_width + expr_width + 1 > 80 {
Consider changing the hardcoded value of `80` to use `settings.max_line_length` instead, so that formatting is configurable.

2025-02-05 09:32 UTC, csgui commented on components/clarinet-format/src/formatter/mod.rs
> +        acc.to_owned()
`acc` is already an owned String. Probably you can simply return `acc` without invoking `.to_owned()`, which avoids extra allocations.

2025-02-05 09:32 UTC, csgui commented on components/clarinet-format/src/formatter/ignored.rs
> +            println!("trait ref: {}", name);
Can that be replaced by `format!()` or do we really need to print that information to the console?

2025-02-05 11:25 UTC, hugocaillard commented on components/clarinet-format/tests/golden-intended/clarity-bitcoin.clar
> +					)
Beyond just stacking closing parens, I think we don't need to introcude new line before each opening one `(`
If the value was not a tuple (or was a variable name), it would easily fit on one line
```clarity
(parsed-u64 (try! (read-uint64 value)))
```

Here, I'd say we want to split the tuple into multiple lines for readability, but it doesn't imply splitting the rust of the line
```clarity
(parsed-u64 (try! (read-uint64 {
  txbuff: tx,
  index: (+ u1 ptr)
 })))
 ```
 
 
What do you think?

2025-02-05 11:28 UTC, hugocaillard commented on components/clarinet-format/tests/golden-intended/clarity-bitcoin.clar
> +			{
Yes that was my point
```
(ok {
  k1: 1
  k2: 2
})
```

Instead of
(ok
  {
    k1: 1
    k2: 2
  }
)
```

2025-02-05 15:24 UTC, tippenein commented on components/clarinet-format/src/formatter/ignored.rs
> +        let expr_str = display_pse_unformatted(expr);
yes, `format-ignore` is unimplemented as of now

2025-02-05 18:51 UTC, hugocaillard reviewed
Some more comments/questions

2025-02-05 22:53 UTC, hugocaillard reviewed
More golden tests comments

2025-02-05 22:53 UTC, hugocaillard commented on components/clarinet-format/tests/golden-intended/clarity-bitcoin.clar
> +		)
```suggestion
  (ctx {
    txbuff: tx,
    index: u0
  })
```

The opening `(` and `{` are on the same indentation level, so should be the closing one

2025-02-05 22:53 UTC, hugocaillard commented on components/clarinet-format/tests/golden-intended/clarity-bitcoin.clar
> +						)
There are some places where i think the line splitting logic could be improved.
I think it would be nice to have some sort of rule like "if a function call doesn't fit on one line, all arguments should be split on new ones", instead of the just last one like here.

So instead of
```clarity
(unwrap-panic
  (slice? (list u0 u1 u2 u3 u4 u5 u6 u7 u8 u9 u10 u11 u12 u13) u0
    (get tree-depth proof)
  )
)
```

Something like:
```clarity
(unwrap-panic
  (slice?
    (list u0 u1 u2 u3 u4 u5 u6 u7 u8 u9 u10 u11 u12 u13)
    u0
    (get tree-depth proof)
  )
)
```


--- 

I think more "one-lining" could be done, but this is already being discussed [here](https://github.com/hirosystems/clarinet/pull/1609/files#r1942697216)
```clarity
(unwrap-panic (slice?
  (list u0 u1 u2 u3 u4 u5 u6 u7 u8 u9 u10 u11 u12 u13)
  u0
  (get tree-depth proof)
))
```

2025-02-05 22:53 UTC, hugocaillard commented on components/clarinet-format/tests/golden-intended/clarity-bitcoin.clar
> +						)
Also the rule "if a function call doesn't fit on one line, all arguments should be split on new ones", does have exception for control flow functions like `match`, `if` where the first arg is on the samel line, but that seems to be working well

2025-02-06 16:40 UTC, tippenein commented on components/clarinet-format/tests/golden-intended/clarity-bitcoin.clar
> +				}
ah! Definitely agree. Didn't know that was accepted in clarity.. that's great. Probably easier for me to remove the comma special casing across all the code and then update the tests that fail

2025-02-10 16:45 UTC, tippenein commented on components/clarinet-format/tests/golden-intended/alex-transfer.clar
> +                )
We handled this on a call. the double indent is gone now. resolving this issue

2025-02-12 19:32 UTC, hugocaillard requested changes
Looking very good, I find the code really readable and I think it will be reasonably to maintain.
Left a few comments/suggestions

2025-02-12 19:32 UTC, hugocaillard commented on components/clarinet-format/src/formatter/mod.rs
> +    fn format_constant(&self, exprs: &[PreSymbolicExpression]) -> String {
I tried
```rs
let result = format_with_default(&String::from("(define-fungible-token hello)"));
```

But it seems to fail.
The second param is options in `define-fungible-token`

2025-02-12 19:32 UTC, hugocaillard commented on components/clarinet-format/src/formatter/mod.rs
> +    // TODO: This should be rolled into format_key_value_sugar, but the PSE
that's alright imo. I feel like in certain context (asts manipulation), a bit a duplication is better than to much abstraction

2025-02-12 19:32 UTC, hugocaillard commented on components/clarinet-format/src/formatter/mod.rs
> +            }
Ideally, integration tests should leave in the [`./tests` directory](https://doc.rust-lang.org/book/ch11-03-test-organization.html#the-tests-directory) (close the golden/golden-intended contracts actually)
We don't do a very good job at doin this in the repo, but we aim to do better.

(Only if this is not too involved to move this test)

2025-02-12 19:40 UTC, tippenein commented on components/clarinet-format/src/formatter/mod.rs
> +    }
it was only because of the specific file/section methods. Seemed like format_file should be the default and `format` should be a method included on this

2025-02-12 19:41 UTC, tippenein commented on components/clarinet-format/src/formatter/mod.rs
> +                            _ => {
oooo, yea. That's a _big_ list 😆 Let's see how that looks

2025-02-12 19:42 UTC, tippenein commented on components/clarinet-format/src/formatter/mod.rs
> +            panic!("Expected a valid constant definition with (name value)")
Yes, I should remove all these panics ideally. I had them in while i was writing it so i'd know which loop was failing

2025-02-12 19:49 UTC, tippenein commented on components/clarinet-format/src/formatter/mod.rs
> +    pub fn format_section(&self, source: &str) -> String {
We should be able to format selected sections of code with this. I believe we'll need to pre-populate the `previous_indentation` but I'l' at least add a note for that now.

2025-02-12 20:00 UTC, tippenein commented on components/clarinet-format/src/formatter/mod.rs
> +    fn format_constant(&self, exprs: &[PreSymbolicExpression]) -> String {
Didn't realize that. easy fix. It uses this dumb function called `name_and_args` which i should really remove because it's just asking for trouble

2025-02-13 01:10 UTC, tippenein commented on components/clarinet-format/tests/golden-intended/clarity-bitcoin.clar
> +		)
Ok, I did some hacking around this and it's hard to get something that works both deterministically and with paired closing brackets/parens.

For example we can use this basic idea to match the closing at the end of an expression, but it relies on span information
```
        let mut break_lines = false;
        let start_line = list[0].span().start_line;
        for expr in list.iter() {
            if expr.span().start_line != start_line {
                break_lines = true;
            }
```

That means that we lose determinism.

For example:

```
(try! (ok (list .... ))
;; formatted
(try!
  (ok (list 
    1 2 3...
    )
))
```

will be max-line-length closed differently than 

```
(try! 
  (ok (list 1 2 3..))
)
;; formatted
(try!
  (ok (list 
    1 2 3...
  ))
)


  
  ```

2025-02-13 11:31 UTC, hugocaillard commented on components/clarinet-format/tests/golden-intended/clarity-bitcoin.clar
> +		)
Could there be another approach where we don't consider the spans of the input at all. Or, said differently, we always one-line the input whatever it is
```clarity
;; input 1
(try!
  (ok (list 1 2 3..))
)
;; input 2
(try!
  (ok (list 1 2 3..)))
;; input 3
(try!  (ok (list 1 2 3..)))

 ;; would all be considered like so:
(try! (ok (list 1 2 3..)))
```

Then, the job of the formatter is to insert breaklines where it's needed
And, by keeping track of the parenthesis pairs, put the closing parens on the same indentation level as the opening one.

Although, maybe I'm over simplying this, or what I'm suggesting doesn't really fit in the current design of the formatter.

--- 

Note: in your comment i don't really understand this example
```clar
(try! (ok (list .... ))
;; formatted
(try!
  (ok (list 
    1 2 3...
    )
))
```
Why is the first `)` indented twice?
Why is the second `)` not intended? 
It sounds to me that they are both wrong (when with an extra indent and one with a missing one)

2025-02-13 15:45 UTC, tippenein commented on components/clarinet-format/tests/golden-intended/clarity-bitcoin.clar
> +		)
Ya, sorry. Bad example.

```
(try! (ok 
  (list 1 2 3
    4 5 6...
  )
))
```

Point was really just about the span checking messing up determinism. We can figure out the closing parens in the case the max-line-length isn't reached, but in that case we have an issue with the current wrapping.

I think you're right though. The current wrapping logic is too simplistic

2025-02-18 15:45 UTC, tippenein commented on components/clarinet-cli/src/frontend/cli.rs
> +        Command::Formatter(cmd) => {
> This command is in beta. Feedback is welcome!

2025-02-18 16:19 UTC, hugocaillard reviewed
Remarks on intended-golden

2025-02-18 16:19 UTC, hugocaillard commented on components/clarinet-format/tests/golden-intended/alex-transfer.clar
> +                            ))
```suggestion
                            )
                        )
```

The unwrap-panic closing parens should have 1 less indentation level

2025-02-18 16:19 UTC, hugocaillard commented on components/clarinet-format/tests/golden-intended/clarity-bitcoin.clar
> +      })
The opening `(` has one less indentation level.
Although it would work to have both on the same

2025-02-18 16:19 UTC, hugocaillard commented on components/clarinet-format/tests/golden-intended/clarity-bitcoin.clar
> +      })
```suggestion
    (ok {
			uint8: (buff-to-uint-le
				(unwrap-panic
					(as-max-len?
						(unwrap! (slice? data base (+ base u1)) (err ERR-OUT-OF-BOUNDS))
						u1
					))
			),
			ctx: {
				txbuff: data,
				index: (+ u1 base),
			},
		})
```

2025-02-18 17:06 UTC, hugocaillard approved these changes
Let's ship it! 🚀

2025-02-18 17:53 UTC, merged

2025-02-18 18:26 UTC, hugocaillard commented
Thanks @csgui.
We merged a bit quickly to get it ready for the release 👌