Docs ### Interacting with contracts deployed on Mainnet
hirosystems/clarinet pull request #502
Opened 2022-07-29 13:14 UTC by dabuchera

Hi,

Was refining a bit the docs about the interacting with contract deployed on Mainnet. 
Mainly elaborating with a short example but also changing the syntax of adding requirements. 

Best,

2022-08-01 15:07 UTC, obycode requested changes
Thanks @dabuchera for this PR! I've added a few comments and suggestions.

2022-08-02 18:54 UTC, dabuchera commented on README.md
> +Dependencies from **internal** contracts should be set in `depends_on`
I once speculated that, but was not sure. I will document that as deprecated but often seen in tutorials and documentation.

2022-08-02 18:56 UTC, dabuchera commented on README.md
> +Similar to the deployment on Mainnet, the requirements should be listed in the manifest `Clarinet.toml`
Agree

2022-08-02 19:00 UTC, dabuchera commented on README.md
> +
Agree

2022-08-02 19:00 UTC, dabuchera commented on README.md
> +
Agree

2022-08-08 16:05 UTC, obycode requested changes
Thanks for the updates! Just one minor change requested.

2022-08-08 16:05 UTC, obycode commented on README.md
> +#depends_om = ["conversion","conversion-v2"] #optional deprecated
```suggestion
# depends_on = ["conversion","conversion-v2"] # no longer needed, ignored if provided
```

2022-08-09 13:22 UTC, obycode approved these changes
Thanks!

2022-08-09 14:10 UTC, merged