Docs: Added topics to all the articles to increase visibility
hirosystems/clarinet pull request #888
Opened 2023-02-15 20:21 UTC by LakshmiLavanyaKasturi

Added topics section at the top of all the articles to increase visibility. 
Reference: https://www.notion.so/hiropbc/Docs-Topics-949d9801db2f4441b38f0ebbc3bd6c81?pvs=4

# Relates to https://github.com/hirosystems/docs/issues/272

2023-02-15 21:26 UTC, trichards-hiro reviewed
@LakshmiLavanyaKasturi I have a question about the Topics for each page. Do you think we should have a heading for each topic? What I mean is, or example, if a topic is "Install Clarinet," should we have a heading called "Install Clarinet" so there is a consistency throughout the document. I did not add comments for each page, but thought I would bring this up in case we wanted to make sure that there is a heading on the page for each topic.

2023-02-15 21:26 UTC, trichards-hiro commented on docs/feature-guides/chainhooks.md
> +- [x] Chainhooks design
```suggestion
- [x] Design
```

2023-02-15 21:26 UTC, trichards-hiro commented on docs/feature-guides/analyze-with-check-checker.md
> +
@LakshmiLavanyaKasturi Should we add a Heading here for 'Enable static analysis pass"?

2023-02-15 21:26 UTC, trichards-hiro commented on docs/feature-guides/extend-clarinet.md
> +- [x] Use clanet run command
```suggestion
- [x] Use clarinet run command
```

2023-02-15 22:18 UTC, LakshmiLavanyaKasturi commented
> Per our 1:1 conversation, we will leave it as is and not include any extra headings. The intent is to keep the "Topics" and the right nav different.

2023-02-16 17:22 UTC, hugocaillard requested changes
Left a few remarks / suggestions.

Some of the topics sounds a bit generic/vague

2023-02-16 18:40 UTC, LakshmiLavanyaKasturi commented on docs/feature-guides/chainhooks.md
> +- [x] Design
Changed it to Chainhooks design.

2023-02-16 18:41 UTC, LakshmiLavanyaKasturi commented on docs/how-to-guides/how-to-run-integration-environment.md
> +- [x] Participate in stacking
I changed it to Stacking orders to avoid any confusion.

2023-02-16 18:42 UTC, LakshmiLavanyaKasturi commented on docs/how-to-guides/how-to-run-integration-environment.md
> +- [x] Participate in stacking
> Per our chat, changed it to Stacking on Devnet.

2023-02-16 21:24 UTC, trichards-hiro submitted a review, later dismissed

2023-02-16 21:47 UTC, sabbyanandan requested changes
I can see how the "topics" can be helpful to readers; however, we can make the bullets a bit more aligned with the product-centered language and tighten it up. 

I left a few suggestions as to how on a few sections. Also, when we are referring to commands, let's list the command exactly and not word it differently.

2023-02-16 21:47 UTC, sabbyanandan commented on docs/feature-guides/clarinet-deploy.md
> +- [x] Plan primities
```suggestion
- [x] Plan primitives
```

2023-02-16 21:47 UTC, sabbyanandan commented on docs/feature-guides/clarinet-integrate.md
> +- [x] Understand Clarinet integration
`clarinet integrate` is a command, and here it makes it sound like some sort of an integration; perhaps we can define it differently (example "What is `clarinet integrate`?")

2023-02-16 21:47 UTC, sabbyanandan commented on docs/how-to-guides/how-to-debug-contract.md
> +- [x] Identify command-line debugger inside the console
```suggestion
- [x] Use command-line debugger inside the `clarinet console`
```

2023-02-16 21:47 UTC, sabbyanandan commented on docs/how-to-guides/how-to-debug-contract.md
> +- [x] Explore execution trace command
```suggestion
- [x] Learn how to use `trace` command
```

2023-02-16 21:47 UTC, sabbyanandan commented on docs/how-to-guides/how-to-deploy-contracts.md
> +- [x] Generate deplayment plan
```suggestion
- [x] Generate deployment plan
```

2023-02-16 21:47 UTC, sabbyanandan commented on docs/how-to-guides/how-to-deploy-with-subnets.md
> +- [x] Enable subnet node
All references can be "subnets"

2023-02-16 21:47 UTC, sabbyanandan commented on docs/how-to-guides/how-to-run-integration-environment.md
> +- [x] Launch Devnet interface and configuration
```suggestion
- [x] Launch Clarinet with Devnet
```

2023-02-17 13:35 UTC, hugocaillard commented on docs/getting-started.md
> +- [x] Build Clarinet from source using Cargo
```suggestion
- [x] Build Clarinet from source
```

We may want to keep it short?

2023-02-17 13:36 UTC, hugocaillard submitted a review, later dismissed
lgtm

2023-02-22 19:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/hirosystems/clarinet?pullRequest=888) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/hirosystems/clarinet?pullRequest=888) before we can accept your contribution.<br/>**3** out of **4** committers have signed the CLA.<br/><br/>:white_check_mark: hugocaillard<br/>:white_check_mark: LakshmiLavanyaKasturi<br/>:white_check_mark: sabbyanandan<br/>:x: mefrem<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/hirosystems/clarinet?pullRequest=888) it.</sub>

2023-02-22 19:59 UTC, hugocaillard commented
Lots of conflicts, apparently due to many commits and modifications on the same files between @mefrem and @LakshmiLavanyaKasturi 
I think all of the comments have address so I squashed the commits and fix conflicts in another branch, cf #902 

If you are ok to merge #902,  I think we can close this one

2023-02-22 22:37 UTC, closed without merging